apiVersion: apps/v1
kind: Depoyment
metadata: 
   name: myapp-deployment
   labels: 
     tier: frontend
     app: myapp
spec:
  selector:
     matchLables:
        app: myapp
  replicas: 4
  template:
    metadata:
      name: nginx-2
      labels:
          app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx